const data = [
  {
    id: 1,
    name: "Addidas Blue",
    newPrice: 100,
    oldPrice: 500,
    description: "Addidas Blue description",
    img: "image1.jpg",
    rating: 4,
  },
  {
    id: 2,
    name: "Addidas Red",
    newPrice: 200,
    oldPrice: 500,
    description: "Addidas red description ",
    img: "image2.jpg",
  },
  {
    id: 3,
    name: "Addidas Pink",
    newPrice: 300,
    oldPrice: 500,
    description: "Addidas pink description ",
    img: "image3.jpg",
  },
  {
    id: 4,
    name: "Addidas Pink 4",
    newPrice: 400,
    oldPrice: 500,
    description: "Addidas pink 4 description ",
    img: "image3.jpg",
  },
];
